"""Phase 10 tests — Checkpoint save/restore + undo cascade.

Tests use the real sqlite axi.db (no DB mock in conftest). Each test
that touches the DB uses a fresh tournament_id (auto-generated by
Tournament.__init__) so checkpoint rows don't collide across tests.
"""

import json
import uuid

import pytest

import axi.handlers.checkpoint_handler as cph
import axi.handlers.database_handler as db
from axi.match_node import MatchNode
from axi.tournament import Tournament
from axi.tournament_formats.single_elimination import SingleElimination
from axi.tournament_state import state as tournament_state
from axi.util import (
    MATCH_STATUS_ASLEEP,
    MATCH_STATUS_COMPLETED,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _clean_tournament_state():
    tournament_state.reset()
    yield
    tournament_state.reset()


def make_players(n, p1):
    return [type(p1)(f"p{i}", 2000 + i) for i in range(n)]


def _complete(graph, node, winner):
    idx = node.players.index(winner)
    ft = node.first_to() if node.first_to() > 0 else 1
    score = [0, 0]
    score[idx] = ft
    node.score = score
    return graph.complete_match(node)


# ---------------------------------------------------------------------------
# Schema tables exist
# ---------------------------------------------------------------------------


class TestSchemaTables:
    def test_tourney_checkpoints_table_exists(self):
        cols = db.get_column_names("tourney_checkpoints")
        assert "tourney_id" in cols
        assert "checkpoint_ctr" in cols
        assert "status" in cols
        assert "player_state_str" in cols
        assert "match_checkpoints_str" in cols

    def test_match_checkpoints_table_exists(self):
        cols = db.get_column_names("match_checkpoints")
        assert "match_id" in cols
        assert "tourney_checkpoint_id" in cols
        assert "checkpoint_ctr" in cols
        assert "status" in cols
        assert "user_id_a" in cols
        assert "user_id_b" in cols
        assert "score_a" in cols
        assert "score_b" in cols


# ---------------------------------------------------------------------------
# Serialization helpers
# ---------------------------------------------------------------------------


class TestSerialization:
    def test_user_id_resolves_uid(self, p1):
        assert cph._user_id(p1) == p1.uid.id

    def test_user_id_none_safe(self):
        assert cph._user_id(None) is None

    def test_hash_node_id_stable(self):
        h1 = cph._hash_node_id("abc")
        h2 = cph._hash_node_id("abc")
        assert h1 == h2

    def test_hash_node_id_different_for_different_inputs(self):
        h1 = cph._hash_node_id("abc")
        h2 = cph._hash_node_id("abd")
        assert h1 != h2

    def test_hash_node_id_none_returns_zero(self):
        assert cph._hash_node_id(None) == 0

    def test_serialize_rating_with_object(self):
        class FakeRating:
            mu = 300.0
            sigma = 100.0
        assert cph._serialize_rating((0, FakeRating())) == [0, 300.0, 100.0]

    def test_serialize_rating_none(self):
        assert cph._serialize_rating(None) is None


# ---------------------------------------------------------------------------
# save_checkpoint
# ---------------------------------------------------------------------------


class TestSaveCheckpoint:
    def test_returns_rowid(self):
        t = Tournament(title="X", scope="ch", seed=42)
        rowid = cph.save_checkpoint(t)
        assert isinstance(rowid, int)
        assert rowid > 0

    def test_increments_ctr(self):
        t = Tournament(title="X", scope="ch", seed=42)
        assert t.checkpoint_ctr == 0
        cph.save_checkpoint(t)
        assert t.checkpoint_ctr == 1
        cph.save_checkpoint(t)
        assert t.checkpoint_ctr == 2

    def test_sets_checkpoint_id(self):
        t = Tournament(title="X", scope="ch", seed=42)
        rowid = cph.save_checkpoint(t)
        assert t.checkpoint_id == rowid

    def test_persists_to_db(self):
        t = Tournament(title="X", scope="ch", seed=42)
        cph.save_checkpoint(t)
        row = db.load_entries_where(
            "tourney_checkpoints", "tourney_id", t.tournament_id)
        assert len(row) >= 1


# ---------------------------------------------------------------------------
# load_latest_checkpoint
# ---------------------------------------------------------------------------


class TestLoadLatestCheckpoint:
    def test_returns_none_for_missing(self):
        result = cph.load_latest_checkpoint("nonexistent-tid")
        assert result is None

    def test_returns_latest_by_ctr(self):
        t = Tournament(title="X", scope="ch", seed=42)
        cph.save_checkpoint(t)
        cph.save_checkpoint(t)
        cph.save_checkpoint(t)
        row = cph.load_latest_checkpoint(t.tournament_id)
        assert row is not None
        # Latest is the 3rd save (ctr=2 since 0-indexed).
        assert row["checkpoint_ctr"] == 2

    def test_row_includes_player_state_str(self):
        t = Tournament(title="X", scope="ch", seed=42)
        cph.save_checkpoint(t)
        row = cph.load_latest_checkpoint(t.tournament_id)
        assert isinstance(row["player_state_str"], str)
        data = json.loads(row["player_state_str"])
        assert "players" in data
        assert "drop_dict" in data


# ---------------------------------------------------------------------------
# restore_tournament
# ---------------------------------------------------------------------------


class TestRestoreTournament:
    def test_returns_none_for_missing(self):
        result = cph.restore_tournament("nonexistent", lambda uid: None)
        assert result is None

    def test_restores_tournament_id(self, p1):
        t = Tournament(title="X", scope="ch", seed=42)
        cph.save_checkpoint(t)
        restored = cph.restore_tournament(
            t.tournament_id, lambda uid: None)
        assert restored.tournament_id == t.tournament_id

    def test_restores_players(self, p1, p2):
        t = Tournament(title="X", scope="ch", seed=42)
        t.players = [p1, p2]
        cph.save_checkpoint(t)
        users_db = {p1.uid.id: p1, p2.uid.id: p2}
        restored = cph.restore_tournament(
            t.tournament_id, lambda uid: users_db.get(uid))
        assert len(restored.players) == 2
        assert p1 in restored.players
        assert p2 in restored.players

    def test_restores_drop_dict(self, p1, p2):
        t = Tournament(title="X", scope="ch", seed=42)
        t.players = [p1, p2]
        t.drop_dict[p1].append(0)
        cph.save_checkpoint(t)
        users_db = {p1.uid.id: p1, p2.uid.id: p2}
        restored = cph.restore_tournament(
            t.tournament_id, lambda uid: users_db.get(uid))
        assert p1 in restored.drop_dict
        assert restored.drop_dict[p1] == [0]

    def test_restores_dq_dict(self, p1, p2):
        t = Tournament(title="X", scope="ch", seed=42)
        t.players = [p1, p2]
        t.dq_dict[p2].append(1)
        cph.save_checkpoint(t)
        users_db = {p1.uid.id: p1, p2.uid.id: p2}
        restored = cph.restore_tournament(
            t.tournament_id, lambda uid: users_db.get(uid))
        assert p2 in restored.dq_dict
        assert restored.dq_dict[p2] == [1]

    def test_restores_checkins_post_id(self):
        t = Tournament(title="X", scope="ch", seed=42)
        t.checkins_post_id = 999
        cph.save_checkpoint(t)
        restored = cph.restore_tournament(t.tournament_id, lambda uid: None)
        assert restored.checkins_post_id == 999

    def test_missing_user_skipped(self, p1):
        t = Tournament(title="X", scope="ch", seed=42)
        t.players = [p1]
        cph.save_checkpoint(t)
        # Lookup returns None for all users.
        restored = cph.restore_tournament(
            t.tournament_id, lambda uid: None)
        assert restored.players == []


# ---------------------------------------------------------------------------
# MatchNode.undo
# ---------------------------------------------------------------------------


class TestMatchNodeUndo:
    def test_clears_score_and_status(self):
        node = MatchNode(tournament_id="t", graph_id="g",
                         players=[], status=MATCH_STATUS_COMPLETED,
                         score=[2, 0])
        node.undo()
        assert node.status == MATCH_STATUS_ASLEEP
        assert node.score == [0, 0]

    def test_clears_checkins_and_reports(self):
        node = MatchNode(tournament_id="t", graph_id="g", players=[])
        node.checkins.add("user1")
        node.reports["user1"] = (2, 0)
        node.undo()
        assert node.checkins == set()
        assert node.reports == {}

    def test_clears_checkin_deadline(self):
        node = MatchNode(tournament_id="t", graph_id="g", players=[])
        node.checkin_deadline = 9999
        node.undo()
        assert node.checkin_deadline is None


# ---------------------------------------------------------------------------
# MatchGraph.undo_match cascade
# ---------------------------------------------------------------------------


class TestUndoMatch:
    def test_undo_resets_node(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_undo_test" not in PRESETS:
            @register_preset("se_undo_test")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"

        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_undo_test")
        t.begin()
        graph = t.current_phase()
        active = [n for n in graph.nodes_by_id.values()
                  if n.awake() and n.label != "VICTORY"]
        node = active[0]
        winner = node.players[0]
        _complete(graph, node, winner)
        assert node.completed()
        graph.undo_match(node)
        assert node.status == MATCH_STATUS_ASLEEP
        assert node.score == [0, 0]

    def test_undo_releases_placement(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_undo_test2" not in PRESETS:
            @register_preset("se_undo_test2")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_undo_test2")
        t.begin()
        graph = t.current_phase()
        active = [n for n in graph.nodes_by_id.values()
                  if n.awake() and n.label != "VICTORY" and n.loser_gets is not None]
        if not active:
            pytest.skip("no node with loser_gets in this preset config")
        node = active[0]
        loser = node.players[1]
        _complete(graph, node, node.players[0])
        # Loser got placed.
        assert graph.placements_dict.get(loser) == node.loser_gets
        graph.undo_match(node)
        # Placement released.
        assert graph.placements_dict.get(loser, -1) == -1


# ---------------------------------------------------------------------------
# MatchGraph.undo_drop_user / undo_dq_user
# ---------------------------------------------------------------------------


class TestUndoDropDq:
    def test_undo_drop_no_op_when_not_dropped(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_undo_drop_test" not in PRESETS:
            @register_preset("se_undo_drop_test")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_undo_drop_test")
        t.begin()
        graph = t.current_phase()
        # User not in drop_dict; undo_drop_user is a no-op.
        result = graph.undo_drop_user(t.players[0])
        assert result == []

    def test_undo_drop_removes_from_drop_dict(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_undo_drop_test2" not in PRESETS:
            @register_preset("se_undo_drop_test2")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_undo_drop_test2")
        t.begin()
        graph = t.current_phase()
        user = t.players[0]
        t.drop_user(user)
        assert user in t.drop_dict
        graph.undo_drop_user(user)
        assert user not in t.drop_dict

    def test_undo_dq_removes_from_dq_dict(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_undo_dq_test" not in PRESETS:
            @register_preset("se_undo_dq_test")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_undo_dq_test")
        t.begin()
        graph = t.current_phase()
        user = t.players[0]
        t.dq_user(user)
        assert user in t.dq_dict
        graph.undo_dq_user(user)
        assert user not in t.dq_dict


# ---------------------------------------------------------------------------
# Tournament.undo_phase
# ---------------------------------------------------------------------------


class TestUndoPhase:
    def test_undo_phase_decrements_phase_id(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_undo_phase_test" not in PRESETS:
            @register_preset("se_undo_phase_test")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_undo_phase_test")
        t.begin()
        assert t.phase_id == 0
        # Single-phase preset; undo brings us back to -1.
        t.undo_phase()
        assert t.phase_id == -1

    def test_undo_phase_no_op_when_no_phases(self):
        t = Tournament(title="T", scope="ch", seed=42)
        result = t.undo_phase()
        assert result == []


# ---------------------------------------------------------------------------
# Auto-checkpoint hooks
# ---------------------------------------------------------------------------


class TestAutoCheckpointHooks:
    def test_advance_phase_saves_checkpoint(self, p1):
        from axi.tournament_presets import register_preset, PRESETS
        if "se_autosave_test" not in PRESETS:
            @register_preset("se_autosave_test")
            def _preset(_t):
                return [lambda tt, ps: SingleElimination(tt, ps, stream=False)], "SE"
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        t.preset("se_autosave_test")
        initial_ctr = t.checkpoint_ctr
        t.begin()
        # advance_phase fires inside begin → save_checkpoint hook fires.
        assert t.checkpoint_ctr > initial_ctr

    def test_drop_user_saves_checkpoint(self, p1):
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        initial_ctr = t.checkpoint_ctr
        t.drop_user(t.players[0])
        assert t.checkpoint_ctr > initial_ctr

    def test_dq_user_saves_checkpoint(self, p1):
        t = Tournament(title="T", scope="ch", seed=42)
        t.add_players(make_players(4, p1))
        initial_ctr = t.checkpoint_ctr
        t.dq_user(t.players[0])
        assert t.checkpoint_ctr > initial_ctr


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    def test_save_checkpoint_with_no_phase(self):
        # Tournament has no phases yet — should still save successfully.
        t = Tournament(title="X", scope="ch", seed=42)
        rowid = cph.save_checkpoint(t)
        assert rowid is not None

    def test_save_checkpoint_returns_none_on_error(self):
        # Tournament.save_checkpoint wraps in try/except, returns None on error.
        # We can't easily simulate a DB error; just verify no crash on edge inputs.
        t = Tournament(title="X", scope="ch", seed=42)
        result = t.save_checkpoint()
        # Either an int rowid or None — never raises.
        assert isinstance(result, int) or result is None

    def test_restore_after_multiple_saves_returns_latest(self):
        t = Tournament(title="X", scope="ch", seed=42)
        cph.save_checkpoint(t)
        t.checkins_post_id = 100
        cph.save_checkpoint(t)
        t.checkins_post_id = 200
        cph.save_checkpoint(t)
        restored = cph.restore_tournament(t.tournament_id, lambda uid: None)
        assert restored.checkins_post_id == 200
